In [2]:
import pandas as pd

In [3]:
my_data = pd.read_csv("Top_This_Week.csv")
my_data

ID                                                url  \
0   14mo2g0                https://i.redd.it/xwyomcqbi29b1.jpg   
1   14llabn                    https://v.redd.it/w6s5ehaxqt8b1   
2   14n378b  https://www.cnbc.com/2023/06/30/supreme-court-...   
3   14l8j3k                https://i.redd.it/qcf3y93g8r8b1.png   
4   14lx2do                https://i.redd.it/l1vb7439gw8b1.jpg   
..      ...                                                ...   
95  14q3zm1  https://www.reddit.com/r/wallstreetbets/commen...   
96  14pt4eq  https://www.reddit.com/r/wallstreetbets/commen...   
97  14lngwo  https://teamster.org/2023/06/teamsters-nationw...   
98  14pjr3j  https://www.reuters.com/technology/amds-ai-chi...   
99  14nbryb             https://www.reddit.com/gallery/14nbryb   

                                                Title  Total Comments  Score  
0                  The Future of investment expertise             650  32219  
1    Musk vs Zuckerberg. The fight of the Century !!!             496  12661  
2   Supreme Court strikes down student loan forgiv...            3024  10994  
3   Home prices in the US declined for the first t...            1166  10699  
4        My therapist tells me to join this sub. Why?             312   8427  
..                                                ...             ...    ...  
95                   The Bull Market is Just Starting             349    199  
96           Group Barbeque Thread for July 4th, 2023            5798    173  
97       Teamsters: Nationwide UPS Strike is Imminent              59    173  
98  AMD AI chips could match Nvidia offerings, sof...              69    174  
99                         Tim Apple $AAPL 40k YOLO🍎🍏              53    155  

[100 rows x 5 columns]

In [4]:
import praw
import os
import pandas as pd
from dotenv import load_dotenv
import datetime
from praw.models import MoreComments

# loading env file
load_dotenv('environment.env')


reddit = praw.Reddit(client_id = os.getenv('CLIENT_ID'),
                    client_secret = os.getenv('CLIENT_SECRET'),
                    user_agent = os.getenv('USER_AGENT'))



ids = my_data["ID"]
comments = {"Post ID" : [], "Date" : [], "Num_Comments" : [], "Comments" : []}

for id in ids:
    submission = reddit.submission(id = id)
    comments["Post ID"].append(id)
    comments["Date"].append(datetime.datetime.utcfromtimestamp(submission.created_utc))
    comments["Num_Comments"].append(submission.num_comments)
    comments_array = []
    for commentInstance in submission.comments[1:]:
        if isinstance(commentInstance, MoreComments):
            continue
        comments_array.append(commentInstance.body)
    comments["Comments"].append(comments_array)

comments_df = pd.DataFrame(comments)
comments_df


Post ID                Date  Num_Comments  \
0   14mo2g0 2023-06-30 02:38:33           650   
1   14llabn 2023-06-28 21:11:26           496   
2   14n378b 2023-06-30 15:16:01          3030   
3   14l8j3k 2023-06-28 12:44:00          1166   
4   14lx2do 2023-06-29 06:16:13           310   
..      ...                 ...           ...   
95  14q3zm1 2023-07-04 03:50:09           442   
96  14pt4eq 2023-07-03 20:00:34          5822   
97  14lngwo 2023-06-28 22:38:19            59   
98  14pjr3j 2023-07-03 13:56:32            72   
99  14nbryb 2023-06-30 20:52:09            53   

                                             Comments  
0   [https://preview.redd.it/du20cvgfz29b1.jpeg?wi...  
1   [Danm Charlie Sheen was jacked, Nvidia working...  
2   [That means fewer day traders?, Should've take...  
3   [wow awesome. Prices went from "unaffordable" ...  
4   [I’m in this picture and I don’t like it., Sum...  
..                                                ...  
95  [Time to buy puts on everything, The top is in...  
96  [I swear to God I just watched a video where a...  
97  [Im thinking puts bois, Bullish\n\nhttps://pre...  
98  [Real problem for AMD isn’t performance, it’s ...  
99  [It was a $8500 yolo that went to $40k. Congra...  

[100 rows x 4 columns]

In [4]:
print(comments_df.size)
print(comments_df.shape)
print(comments_df.head())

comments_df.to_csv("Comments_df.csv", index=False)

NameError: name 'comments_df' is not defined

In [3]:
# Cleaning comments_df

new_df = pd.read_csv("Comments.csv")
new_df.head()

Post ID                                              Title  \
0  14n378b  Supreme Court strikes down student loan forgiv...   
1  14n378b  Supreme Court strikes down student loan forgiv...   
2  14n378b  Supreme Court strikes down student loan forgiv...   
3  14n378b  Supreme Court strikes down student loan forgiv...   
4  14n378b  Supreme Court strikes down student loan forgiv...   

                  Date                                            Comment  
0  2023-06-30 15:16:01                      That means fewer day traders?  
1  2023-06-30 15:16:01  Should've taken out a PPP loan and paid ya stu...  
2  2023-06-30 15:16:01  I don't get why they don't just set student lo...  
3  2023-06-30 15:16:01                               Doordash in shambles  
4  2023-06-30 15:16:01       There’s gonna be so many used dodge chargers

In [23]:
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download("stopwords")


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/aadeesh/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [38]:
# nltk.download("punkt")

[nltk_data] Downloading package punkt to /Users/aadeesh/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:

# for i in range(10):
#     print(new_df["Comment"][i])
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def commentCleaner(comment):
    # Remove special symbols, emojis, reddit username mentions, and hyperlinks
    comment = re.sub(r"[^\w\s]|http\S+|www\S+|u/[A-Za-z0-9_-]+", "", comment)
    
    # Tokenize the comment
    tokens = word_tokenize(comment)
    # tokens = comment.split(' ')
    # Remove stop words
    stop_words = set(stopwords.words("english"))
    tokens = [token for token in tokens if token not in stop_words]
    
    # Remove URLs
    tokens = [token for token in tokens if not token.startswith("http")]
    
    # Join the tokens back into a single string
    cleaned_comment = " ".join(tokens)
    
    return cleaned_comment
print(commentCleaner("This is a sample comment. It contains some stop words like the, is, and a. emojis are 🚀, great job u/Demonic_Mercenary"))

This sample comment It contains stop words like emojis great job


In [17]:
from transformers import BertTokenizer
import numpy as np
import torch


def tokenize_comment(comment, max_length):
    # Load the BERT tokenizer
    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    
    # Tokenize the comment
    tokenized_text = tokenizer.batch_encode_plus(
        comment,
        add_special_tokens=True,
        max_length=max_length,
        truncation=True,
        padding="max_length",
        return_attention_mask=True,
        return_tensors='pt'
    )
    
    # Extract the tokenized input IDs and attention mask
    input_ids = tokenized_text['input_ids']
    attention_mask = tokenized_text['attention_mask']
    # input_ids = tf.convert_to_tensor(input_ids)

    return input_ids, attention_mask
text = ["My name is Aadeeesh Sharma My name is Aadeeesh Sharma My name is Aadeeesh Sharma My name is Aadeeesh Sharma My name is Aadeeesh Sharma", 
        "You are a very experienced machine learning expert who can solve any question. How would I write a program to tokenize text to make it suitable for bert sentiment analysis?"]
max_length = 64
input_ids, attention_mask = tokenize_comment(text, max_length) 
print(type(input_ids))
print(input_ids)
print()
print(type(attention_mask))
print(attention_mask)

<class 'torch.Tensor'>
tensor([[  101,  2026,  2171,  2003,  9779, 26095,  9953, 14654,  2026,  2171,
          2003,  9779, 26095,  9953, 14654,  2026,  2171,  2003,  9779, 26095,
          9953, 14654,  2026,  2171,  2003,  9779, 26095,  9953, 14654,  2026,
          2171,  2003,  9779, 26095,  9953, 14654,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [  101,  2017,  2024,  1037,  2200,  5281,  3698,  4083,  6739,  2040,
          2064,  9611,  2151,  3160,  1012,  2129,  2052,  1045,  4339,  1037,
          2565,  2000, 19204,  4697,  3793,  2000,  2191,  2009,  7218,  2005,
         14324, 15792,  4106,  1029,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0

In [11]:
from nltk.tokenize import word_tokenize
text = "God is Great! I won a lottery."
print(word_tokenize(text))

['God', 'is', 'Great', '!', 'I', 'won', 'a', 'lottery', '.']


In [7]:
keywords = ["$TSLA", "TSLA", "Tesla", "tesla", 
            "$AAPL", "AAPL", "aapl", "Apple", "apple", 
            "$NVDA", "NVDA", "Nvidia", "nvidia", 
            "$GOOGL", "GOOGL", "Google", "google", "Alphabet", "alphabet",
            "$AMZN", "AMZN", "Amazon", "amazon"
            "$MSFT", "MSFT", "Microsoft", "microsoft"
            "$META", "META", "Meta", "meta"
            ]

In [5]:
import pandas as pd

comments = pd.read_csv("PastWeekComments.csv")
len(comments.index)

40703

In [8]:
# Filtering our dataframe to get the comments which contain our required keywords
mask = comments['Title'].str.contains('|'.join(keywords), case=False) | \
    comments['Comment'].str.contains('|'.join(keywords), case=False)

# Apply the mask to filter the dataframe
filtered_df = comments[mask]

filtered_df.head()

Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow don't think that this is what any Te...     134  
16       They’re going to fake fight in the metaverse      44  
26  I can't wait for Tesla fan boys to lose all th...      76  
30  I mean I have meta calls right now so i'll go ...      59  
38                         I'm all in on Meta Knight.      26

In [9]:
filtered_df["Length"].describe()

count    7766.000000
mean      105.005279
std       200.085983
min         1.000000
25%        31.000000
50%        60.000000
75%       115.000000
max      6213.000000
Name: Length, dtype: float64

In [10]:
filtered_df.head()

Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow don't think that this is what any Te...     134  
16       They’re going to fake fight in the metaverse      44  
26  I can't wait for Tesla fan boys to lose all th...      76  
30  I mean I have meta calls right now so i'll go ...      59  
38                         I'm all in on Meta Knight.      26

In [32]:
copied_df = filtered_df.copy()

copied_df["Comment"] = filtered_df["Comment"].map(commentCleaner)

copied_df.head()

# filtered_df["Comment"] = filtered_df["Comment"].map(commentCleaner)

# filtered_df.head()
print(copied_df["Comment"][30])

I mean I meta calls right ill go zukk


In [17]:
input_ids, masks = tokenize_comment(copied_df["Comment"], 110)

print(copied_df.head())
print(input_ids)
print(masks)

    Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow dont think Tesla investors mind hear...     134  
16                  Theyre going fake fight metaverse      44  
26  I cant wait Tesla fan boys lose fucking money ...      76  
30              I mean I meta calls right ill go zukk      59  
38                                     Im Meta Knight      26  
tf.Tensor(
[[  101  1045  5064 ...     0     0     0]
 [  101  2027  2890 ...     0     0     0]
 [  101  1045  2064 ...     0     0     0]
 ...
 [  101  1045  2903 ...     0     0     0]
 [  101 29433  7087 ...     0     0     0]
 [  101  2012  2232 ...     0 

In [19]:
from transformers import TFBertForSequenceClassification

model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3cc44cf4-207e-4866-9995-4fd0a1446bcb)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json
All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [19]:
from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly i

In [51]:
test_comment = "God is Great! I won a lottery."

# cleaned_test = commentCleaner(test_comment)
print(test_comment)
# print(cleaned_test)
tokenizer = BertTokenizer.from_pretrained("distilbert-base-uncased")
encoded_input = tokenizer.encode_plus(
    text,
    add_special_tokens=True,
    padding='max_length',
    max_length=128,
    return_tensors='pt'
)


God is Great! I won a lottery.


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'DistilBertTokenizer'. 
The class this function is called from is 'BertTokenizer'.


In [52]:
with torch.no_grad():
    outputs = model(**encoded_input)

predictions = outputs.logits.argmax(dim=1)
sentiment_label = predictions.item()

print(sentiment_label)

1


In [53]:
sentiment_classes = ['Negative',  'Neutral', 'Positive']  # Define your sentiment classes here

print(sentiment_label)
# Map the sentiment label to the corresponding class
sentiment = sentiment_classes[sentiment_label]

print("Predicted Sentiment:", sentiment)

1
Predicted Sentiment: Neutral
