In [2]:
import pandas as pd

In [3]:
my_data = pd.read_csv("Top_This_Week.csv")
my_data

ID                                                url  \
0   14mo2g0                https://i.redd.it/xwyomcqbi29b1.jpg   
1   14llabn                    https://v.redd.it/w6s5ehaxqt8b1   
2   14n378b  https://www.cnbc.com/2023/06/30/supreme-court-...   
3   14l8j3k                https://i.redd.it/qcf3y93g8r8b1.png   
4   14lx2do                https://i.redd.it/l1vb7439gw8b1.jpg   
..      ...                                                ...   
95  14q3zm1  https://www.reddit.com/r/wallstreetbets/commen...   
96  14pt4eq  https://www.reddit.com/r/wallstreetbets/commen...   
97  14lngwo  https://teamster.org/2023/06/teamsters-nationw...   
98  14pjr3j  https://www.reuters.com/technology/amds-ai-chi...   
99  14nbryb             https://www.reddit.com/gallery/14nbryb   

                                                Title  Total Comments  Score  
0                  The Future of investment expertise             650  32219  
1    Musk vs Zuckerberg. The fight of the Century !!!             496  12661  
2   Supreme Court strikes down student loan forgiv...            3024  10994  
3   Home prices in the US declined for the first t...            1166  10699  
4        My therapist tells me to join this sub. Why?             312   8427  
..                                                ...             ...    ...  
95                   The Bull Market is Just Starting             349    199  
96           Group Barbeque Thread for July 4th, 2023            5798    173  
97       Teamsters: Nationwide UPS Strike is Imminent              59    173  
98  AMD AI chips could match Nvidia offerings, sof...              69    174  
99                         Tim Apple $AAPL 40k YOLO🍎🍏              53    155  

[100 rows x 5 columns]

In [3]:
print(comments_df.size)
print(comments_df.shape)
print(comments_df.head())

comments_df.to_csv("Comments_df.csv", index=False)

NameError: name 'comments_df' is not defined

In [6]:
keywords = ["$TSLA", "TSLA", "Tesla", "tesla", 
            "$AAPL", "AAPL", "aapl", "Apple", "apple", 
            "$NVDA", "NVDA", "Nvidia", "nvidia", 
            "$GOOGL", "GOOGL", "Google", "google", "Alphabet", "alphabet",
            "$AMZN", "AMZN", "Amazon", "amazon"
            "$MSFT", "MSFT", "Microsoft", "microsoft"
            "$META", "META", "Meta", "meta"
            ]

In [4]:
import pandas as pd

comments = pd.read_csv("PastWeekComments.csv")
len(comments.index)

40703

In [7]:
# Filtering our dataframe to get the comments which contain our required keywords
mask = comments['Title'].str.contains('|'.join(keywords), case=False) | \
    comments['Comment'].str.contains('|'.join(keywords), case=False)

# Apply the mask to filter the dataframe
filtered_df = comments[mask]

filtered_df.head()

Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow don't think that this is what any Te...     134  
16       They’re going to fake fight in the metaverse      44  
26  I can't wait for Tesla fan boys to lose all th...      76  
30  I mean I have meta calls right now so i'll go ...      59  
38                         I'm all in on Meta Knight.      26

In [9]:
filtered_df["Length"].describe()
filtered_df.to_csv("Filtered.csv")

In [10]:
filtered_df.head()

Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow don't think that this is what any Te...     134  
16       They’re going to fake fight in the metaverse      44  
26  I can't wait for Tesla fan boys to lose all th...      76  
30  I mean I have meta calls right now so i'll go ...      59  
38                         I'm all in on Meta Knight.      26

In [32]:
copied_df = filtered_df.copy()

copied_df["Comment"] = filtered_df["Comment"].map(commentCleaner)

copied_df.head()

# filtered_df["Comment"] = filtered_df["Comment"].map(commentCleaner)

# filtered_df.head()
print(copied_df["Comment"][30])

I mean I meta calls right ill go zukk


In [17]:
input_ids, masks = tokenize_comment(copied_df["Comment"], 110)

print(copied_df.head())
print(input_ids)
print(masks)

    Post ID                  Title                 Date  \
6   14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
16  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
26  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
30  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   
38  14hdunm  Choose Your Fighter 🚨  2023-06-23 23:58:45   

                                              Comment  Length  
6   I somehow dont think Tesla investors mind hear...     134  
16                  Theyre going fake fight metaverse      44  
26  I cant wait Tesla fan boys lose fucking money ...      76  
30              I mean I meta calls right ill go zukk      59  
38                                     Im Meta Knight      26  
tf.Tensor(
[[  101  1045  5064 ...     0     0     0]
 [  101  2027  2890 ...     0     0     0]
 [  101  1045  2064 ...     0     0     0]
 ...
 [  101  1045  2903 ...     0     0     0]
 [  101 29433  7087 ...     0     0     0]
 [  101  2012  2232 ...     0 